/*
 * file HeadJointSensors.swift
 *
 * This file was generated by classgenerator from head_joint_sensors.gen.
 * DO NOT CHANGE MANUALLY!
 *
 * Copyright © 2020 Carl Lusty & Callum McColl. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials
 *    provided with the distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgement:
 *
 *        This product includes software developed by Carl Lusty & Callum McColl.
 *
 * 4. Neither the name of the author nor the names of contributors
 *    may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * -----------------------------------------------------------------------
 * This program is free software; you can redistribute it and/or
 * modify it under the above terms or under the terms of the GNU
 * General Public License as published by the Free Software Foundation;
 * either version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see http://www.gnu.org/licenses/
 * or write to the Free Software Foundation, Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

//swiftlint:disable superfluous_disable_command
//swiftlint:disable type_body_length
//swiftlint:disable function_body_length
//swiftlint:disable file_length
//swiftlint:disable line_length
//swiftlint:disable identifier_name

/**
 * @brief Body joint positions c struct
 */
public struct HeadJointSensors {

    public var _raw: wb_head_joint_sensors

    public var headYaw: Int16 {
        get {
            return self._raw.headYaw
        } set {
            self._raw.headYaw = newValue
        }
    }

    public var headPitch: Int16 {
        get {
            return self._raw.headPitch
        } set {
            self._raw.headPitch = newValue
        }
    }

    public var computedVars: [String: Any] {
        return [
            "headYaw": self._raw.headYaw,
            "headPitch": self._raw.headPitch
        ]
    }

    public var manipulators: [String: (Any) -> Any] {
        return [:]
    }

    public var validVars: [String: [Any]] {
        return ["_raw": []]
    }

    /**
     * Create a new `wb_head_joint_sensors`.
     */
    public init(headYaw: Int16 = 0, headPitch: Int16 = 0) {
        self._raw = wb_head_joint_sensors()
        self.headYaw = headYaw
        self.headPitch = headPitch
    }

    /**
     * Create a new `wb_head_joint_sensors`.
     */
    public init(_ rawValue: wb_head_joint_sensors) {
        self._raw = rawValue
    }

    /**
     * Create a `wb_head_joint_sensors` from a dictionary.
     */
    public init(fromDictionary dictionary: [String: Any?]) {
        self.init()
        guard
            let headYaw = dictionary["headYaw"] as? Int16,
            let headPitch = dictionary["headPitch"] as? Int16
        else {
            fatalError("Unable to convert \(dictionary) to wb_head_joint_sensors.")
        }
        self.headYaw = headYaw
        self.headPitch = headPitch
    }

}

extension HeadJointSensors: CustomStringConvertible {

    /**
     * Convert to a description String.
     */
    public var description: String {
        var descString = ""
        descString += "headYaw=\(self.headYaw)"
        descString += ", "
        descString += "headPitch=\(self.headPitch)"
        return descString
    }

}

extension HeadJointSensors: Equatable {}

public func == (lhs: HeadJointSensors, rhs: HeadJointSensors) -> Bool {
    return lhs.headYaw == rhs.headYaw
        && lhs.headPitch == rhs.headPitch
}

extension wb_head_joint_sensors: Equatable {}

public func == (lhs: wb_head_joint_sensors, rhs: wb_head_joint_sensors) -> Bool {
    return HeadJointSensors(lhs) == HeadJointSensors(rhs)
}
