/*
 * file Location.swift
 *
 * This file was generated by classgenerator from location.gen.
 * DO NOT CHANGE MANUALLY!
 *
 * Copyright © 2020 Callum McColl. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials
 *    provided with the distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgement:
 *
 *        This product includes software developed by Callum McColl.
 *
 * 4. Neither the name of the author nor the names of contributors
 *    may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * -----------------------------------------------------------------------
 * This program is free software; you can redistribute it and/or
 * modify it under the above terms or under the terms of the GNU
 * General Public License as published by the Free Software Foundation;
 * either version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see http://www.gnu.org/licenses/
 * or write to the Free Software Foundation, Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

//swiftlint:disable superfluous_disable_command
//swiftlint:disable type_body_length
//swiftlint:disable function_body_length
//swiftlint:disable file_length
//swiftlint:disable line_length
//swiftlint:disable identifier_name

#if canImport(swiftfsm)
import swiftfsm
#endif

#if canImport(GUUnits) && canImport(GUCoordinates)
import GUUnits
import GUCoordinates
#endif

/**
 * Provides a common structure for the location of landmarks.
 */
public struct Location {

    public var _raw: wb_location

    public var direction: Int16 {
        get {
            return self._raw.direction
        } set {
            self._raw.direction = newValue
        }
    }

    public var distance: UInt16 {
        get {
            return self._raw.distance
        } set {
            self._raw.distance = newValue
        }
    }

    public var confidence: UInt8 {
        get {
            return self._raw.confidence
        } set {
            self._raw.confidence = newValue
        }
    }

    public var distanceVariance: UInt32 {
        get {
            return self._raw.distanceVariance
        } set {
            self._raw.distanceVariance = newValue
        }
    }

    public var directionVariance: UInt32 {
        get {
            return self._raw.directionVariance
        } set {
            self._raw.directionVariance = newValue
        }
    }

    public var computedVars: [String: Any] {
        return [
            "direction": self._raw.direction,
            "distance": self._raw.distance,
            "confidence": self._raw.confidence,
            "distanceVariance": self._raw.distanceVariance,
            "directionVariance": self._raw.directionVariance
        ]
    }

    public var manipulators: [String: (Any) -> Any] {
        return [:]
    }

    public var validVars: [String: [Any]] {
        return ["_raw": []]
    }

    /**
     * Create a new `wb_location`.
     */
    public init(direction: Int16 = 0, distance: UInt16 = 0, confidence: UInt8 = 0, distanceVariance: UInt32 = 0, directionVariance: UInt32 = 0) {
        self._raw = wb_location()
        self.direction = direction
        self.distance = distance
        self.confidence = confidence
        self.distanceVariance = distanceVariance
        self.directionVariance = directionVariance
    }

    /**
     * Create a new `wb_location`.
     */
    public init(_ rawValue: wb_location) {
        self._raw = rawValue
    }

    /**
     * Create a `wb_location` from a dictionary.
     */
    public init(fromDictionary dictionary: [String: Any?]) {
        self.init()
        guard
            let direction = dictionary["direction"] as? Int16,
            let distance = dictionary["distance"] as? UInt16,
            let confidence = dictionary["confidence"] as? UInt8,
            let distanceVariance = dictionary["distanceVariance"] as? UInt32,
            let directionVariance = dictionary["directionVariance"] as? UInt32
        else {
            fatalError("Unable to convert \(dictionary) to wb_location.")
        }
        self.direction = direction
        self.distance = distance
        self.confidence = confidence
        self.distanceVariance = distanceVariance
        self.directionVariance = directionVariance
    }

    #if canImport(GUUnits) && canImport(GUCoordinates)
    public var relativeCoordinate: RelativeCoordinate {
        RelativeCoordinate(direction: Angle(degrees: direction), distance: Distance(centimetres: distance))
    }

    #endif

}

extension Location: CustomStringConvertible {

    /**
     * Convert to a description String.
     */
    public var description: String {
        var descString = ""
        descString += "direction=\(self.direction)"
        descString += ", "
        descString += "distance=\(self.distance)"
        descString += ", "
        descString += "confidence=\(self.confidence)"
        descString += ", "
        descString += "distanceVariance=\(self.distanceVariance)"
        descString += ", "
        descString += "directionVariance=\(self.directionVariance)"
        return descString
    }

}

extension Location: Equatable {}

public func == (lhs: Location, rhs: Location) -> Bool {
    return lhs.direction == rhs.direction
        && lhs.distance == rhs.distance
        && lhs.confidence == rhs.confidence
        && lhs.distanceVariance == rhs.distanceVariance
        && lhs.directionVariance == rhs.directionVariance
}

extension wb_location: Equatable {}

public func == (lhs: wb_location, rhs: wb_location) -> Bool {
    return Location(lhs) == Location(rhs)
}

#if canImport(swiftfsm)
extension Location: ExternalVariables, KripkeVariablesModifier {}
#endif
