/*
 * file Odometry.swift
 *
 * This file was generated by classgenerator from odometry.gen.
 * DO NOT CHANGE MANUALLY!
 *
 * Copyright © 2020 Dimitri Joukoff. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials
 *    provided with the distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgement:
 *
 *        This product includes software developed by Dimitri Joukoff.
 *
 * 4. Neither the name of the author nor the names of contributors
 *    may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * -----------------------------------------------------------------------
 * This program is free software; you can redistribute it and/or
 * modify it under the above terms or under the terms of the GNU
 * General Public License as published by the Free Software Foundation;
 * either version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see http://www.gnu.org/licenses/
 * or write to the Free Software Foundation, Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

//swiftlint:disable superfluous_disable_command
//swiftlint:disable type_body_length
//swiftlint:disable function_body_length
//swiftlint:disable file_length
//swiftlint:disable line_length
//swiftlint:disable identifier_name

/**
 * Needs to mimic UNSW odometry!
 */
public struct Odometry {

    public var _raw: wb_odometry

    public var forward: Float {
        get {
            return self._raw.forward
        } set {
            self._raw.forward = newValue
        }
    }

    public var left: Float {
        get {
            return self._raw.left
        } set {
            self._raw.left = newValue
        }
    }

    public var turn: Float {
        get {
            return self._raw.turn
        } set {
            self._raw.turn = newValue
        }
    }

    public var computedVars: [String: Any] {
        return [
            "forward": self._raw.forward,
            "left": self._raw.left,
            "turn": self._raw.turn
        ]
    }

    public var manipulators: [String: (Any) -> Any] {
        return [:]
    }

    public var validVars: [String: [Any]] {
        return ["_raw": []]
    }

    /**
     * Create a new `wb_odometry`.
     */
    public init(forward: Float = 0.0, left: Float = 0.0, turn: Float = 0.0) {
        self._raw = wb_odometry()
        self.forward = forward
        self.left = left
        self.turn = turn
    }

    /**
     * Create a new `wb_odometry`.
     */
    public init(_ rawValue: wb_odometry) {
        self._raw = rawValue
    }

    /**
     * Create a `wb_odometry` from a dictionary.
     */
    public init(fromDictionary dictionary: [String: Any?]) {
        self.init()
        guard
            let forward = dictionary["forward"] as? Float,
            let left = dictionary["left"] as? Float,
            let turn = dictionary["turn"] as? Float
        else {
            fatalError("Unable to convert \(dictionary) to wb_odometry.")
        }
        self.forward = forward
        self.left = left
        self.turn = turn
    }

}

extension Odometry: CustomStringConvertible {

    /**
     * Convert to a description String.
     */
    public var description: String {
        var descString = ""
        descString += "forward=\(self.forward)"
        descString += ", "
        descString += "left=\(self.left)"
        descString += ", "
        descString += "turn=\(self.turn)"
        return descString
    }

}

extension Odometry: Equatable {}

public func == (lhs: Odometry, rhs: Odometry) -> Bool {
    return lhs.forward == rhs.forward
        && lhs.left == rhs.left
        && lhs.turn == rhs.turn
}

extension wb_odometry: Equatable {}

public func == (lhs: wb_odometry, rhs: wb_odometry) -> Bool {
    return Odometry(lhs) == Odometry(rhs)
}
