/*
 * file PixelCoordinateLine.swift
 *
 * This file was generated by classgenerator from pixel_coordinate_line.gen.
 * DO NOT CHANGE MANUALLY!
 *
 * Copyright © 2020 Carl Lusty. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials
 *    provided with the distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgement:
 *
 *        This product includes software developed by Carl Lusty.
 *
 * 4. Neither the name of the author nor the names of contributors
 *    may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * -----------------------------------------------------------------------
 * This program is free software; you can redistribute it and/or
 * modify it under the above terms or under the terms of the GNU
 * General Public License as published by the Free Software Foundation;
 * either version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see http://www.gnu.org/licenses/
 * or write to the Free Software Foundation, Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

//swiftlint:disable superfluous_disable_command
//swiftlint:disable type_body_length
//swiftlint:disable function_body_length
//swiftlint:disable file_length
//swiftlint:disable line_length
//swiftlint:disable identifier_name

#if canImport(GUCoordinates)
import GUCoordinates
#endif

/**
 * Class use to represent a single line.
 */
public struct PixelCoordinateLine {

    public var _raw: wb_pixel_coordinate_line

    public var start: PixelCoordinate {
        get {
            return PixelCoordinate(self._raw.start)
        } set {
            self._raw.start = newValue._raw
        }
    }

    public var end: PixelCoordinate {
        get {
            return PixelCoordinate(self._raw.end)
        } set {
            self._raw.end = newValue._raw
        }
    }

    public var computedVars: [String: Any] {
        return [
            "start": self._raw.start,
            "end": self._raw.end
        ]
    }

    public var manipulators: [String: (Any) -> Any] {
        return [:]
    }

    public var validVars: [String: [Any]] {
        return ["_raw": []]
    }

    /**
     * Create a new `wb_pixel_coordinate_line`.
     */
    public init(start: PixelCoordinate = PixelCoordinate(wb_pixel_coordinate()), end: PixelCoordinate = PixelCoordinate(wb_pixel_coordinate())) {
        self._raw = wb_pixel_coordinate_line()
        self.start = start
        self.end = end
    }

    /**
     * Create a new `wb_pixel_coordinate_line`.
     */
    public init(_ rawValue: wb_pixel_coordinate_line) {
        self._raw = rawValue
    }

    /**
     * Create a `wb_pixel_coordinate_line` from a dictionary.
     */
    public init(fromDictionary dictionary: [String: Any]) {
        self.init()
        guard
            let start = (dictionary["start"] as? [String: Any]).flatMap({ PixelCoordinate(fromDictionary: $0)  }),
            let end = (dictionary["end"] as? [String: Any]).flatMap({ PixelCoordinate(fromDictionary: $0)  })
        else {
            fatalError("Unable to convert \(dictionary) to wb_pixel_coordinate_line.")
        }
        self.start = start
        self.end = end
    }

    #if canImport(GUCoordinates)
    public func startPixelCoordinate(resWidth: UInt16, resHeight: UInt16) -> GUCoordinates.PixelCoordinate {
        return start.pixelCoordinate(resWidth: resWidth, resHeight: resHeight)
    }
    #endif
    #if canImport(GUCoordinates)
    public func endPixelCoordinate(resWidth: UInt16, resHeight: UInt16) -> GUCoordinates.PixelCoordinate {
        return end.pixelCoordinate(resWidth: resWidth, resHeight: resHeight)
    }
    #endif

}

extension PixelCoordinateLine: CustomStringConvertible {

    /**
     * Convert to a description String.
     */
    public var description: String {
        var descString = ""
        descString += "start={" + self.start.description + "}"
        descString += ", "
        descString += "end={" + self.end.description + "}"
        return descString
    }

}

extension PixelCoordinateLine: Equatable {}

public func == (lhs: PixelCoordinateLine, rhs: PixelCoordinateLine) -> Bool {
    return lhs.start == rhs.start
        && lhs.end == rhs.end
}

extension wb_pixel_coordinate_line: Equatable {}

public func == (lhs: wb_pixel_coordinate_line, rhs: wb_pixel_coordinate_line) -> Bool {
    return PixelCoordinateLine(lhs) == PixelCoordinateLine(rhs)
}
