/*
 * file SENSORSHeadJointSensors.swift
 *
 * This file was generated by classgenerator from SENSORS_HeadJointSensors.txt.
 * DO NOT CHANGE MANUALLY!
 *
 * Copyright © 2020 Carl Lusty. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials
 *    provided with the distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgement:
 *
 *        This product includes software developed by Carl Lusty.
 *
 * 4. Neither the name of the author nor the names of contributors
 *    may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * -----------------------------------------------------------------------
 * This program is free software; you can redistribute it and/or
 * modify it under the above terms or under the terms of the GNU
 * General Public License as published by the Free Software Foundation;
 * either version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see http://www.gnu.org/licenses/
 * or write to the Free Software Foundation, Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

//swiftlint:disable superfluous_disable_command
//swiftlint:disable type_body_length
//swiftlint:disable function_body_length
//swiftlint:disable file_length
//swiftlint:disable line_length
//swiftlint:disable identifier_name

/**
 * @brief Body joint positions c struct
 */
public struct SENSORSHeadJointSensors {

    public var _raw: wb_sensors_headjointsensors

    public var HeadYaw: Float {
        get {
            return self._raw.HeadYaw
        } set {
            self._raw.HeadYaw = newValue
        }
    }

    public var HeadPitch: Float {
        get {
            return self._raw.HeadPitch
        } set {
            self._raw.HeadPitch = newValue
        }
    }

    public var computedVars: [String: Any] {
        return [
            "HeadYaw": self._raw.HeadYaw,
            "HeadPitch": self._raw.HeadPitch
        ]
    }

    public var manipulators: [String: (Any) -> Any] {
        return [:]
    }

    public var validVars: [String: [Any]] {
        return ["_raw": []]
    }

    /**
     * Create a new `wb_sensors_headjointsensors`.
     */
    public init(HeadYaw: Float = 0.0, HeadPitch: Float = 0.0) {
        self._raw = wb_sensors_headjointsensors()
        self.HeadYaw = HeadYaw
        self.HeadPitch = HeadPitch
    }

    /**
     * Create a new `wb_sensors_headjointsensors`.
     */
    public init(_ rawValue: wb_sensors_headjointsensors) {
        self._raw = rawValue
    }

    /**
     * Create a `wb_sensors_headjointsensors` from a dictionary.
     */
    public init(fromDictionary dictionary: [String: Any]) {
        self.init()
        guard
            let HeadYaw = dictionary["HeadYaw"] as? Float,
            let HeadPitch = dictionary["HeadPitch"] as? Float
        else {
            fatalError("Unable to convert \(dictionary) to wb_sensors_headjointsensors.")
        }
        self.HeadYaw = HeadYaw
        self.HeadPitch = HeadPitch
    }

}

extension SENSORSHeadJointSensors: CustomStringConvertible {

    /**
     * Convert to a description String.
     */
    public var description: String {
        var descString = ""
        descString += "HeadYaw=\(self.HeadYaw)"
        descString += ", "
        descString += "HeadPitch=\(self.HeadPitch)"
        return descString
    }

}

extension SENSORSHeadJointSensors: Equatable {}

public func == (lhs: SENSORSHeadJointSensors, rhs: SENSORSHeadJointSensors) -> Bool {
    return lhs.HeadYaw == rhs.HeadYaw
        && lhs.HeadPitch == rhs.HeadPitch
}

extension wb_sensors_headjointsensors: Equatable {}

public func == (lhs: wb_sensors_headjointsensors, rhs: wb_sensors_headjointsensors) -> Bool {
    return SENSORSHeadJointSensors(lhs) == SENSORSHeadJointSensors(rhs)
}
