/*
 * file SENSORSTorsoJointSensors.swift
 *
 * This file was generated by classgenerator from SENSORS_TorsoJointSensors.txt.
 * DO NOT CHANGE MANUALLY!
 *
 * Copyright © 2020 Carl Lusty & Dimitri Joukoff. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials
 *    provided with the distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgement:
 *
 *        This product includes software developed by Carl Lusty & Dimitri Joukoff.
 *
 * 4. Neither the name of the author nor the names of contributors
 *    may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * -----------------------------------------------------------------------
 * This program is free software; you can redistribute it and/or
 * modify it under the above terms or under the terms of the GNU
 * General Public License as published by the Free Software Foundation;
 * either version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see http://www.gnu.org/licenses/
 * or write to the Free Software Foundation, Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

//swiftlint:disable superfluous_disable_command
//swiftlint:disable type_body_length
//swiftlint:disable function_body_length
//swiftlint:disable file_length
//swiftlint:disable line_length
//swiftlint:disable identifier_name

/**
 * @brief Head and Arm joint positions c struct
 * (Gripper and stiffness not included yet.)
 */
public struct SENSORSTorsoJointSensors {

    public var _raw: wb_sensors_torsojointsensors

    public var HeadYaw: Float {
        get {
            return self._raw.HeadYaw
        } set {
            self._raw.HeadYaw = newValue
        }
    }

    public var HeadPitch: Float {
        get {
            return self._raw.HeadPitch
        } set {
            self._raw.HeadPitch = newValue
        }
    }

    public var LShoulderPitch: Float {
        get {
            return self._raw.LShoulderPitch
        } set {
            self._raw.LShoulderPitch = newValue
        }
    }

    public var LShoulderRoll: Float {
        get {
            return self._raw.LShoulderRoll
        } set {
            self._raw.LShoulderRoll = newValue
        }
    }

    public var LElbowYaw: Float {
        get {
            return self._raw.LElbowYaw
        } set {
            self._raw.LElbowYaw = newValue
        }
    }

    public var LElbowRoll: Float {
        get {
            return self._raw.LElbowRoll
        } set {
            self._raw.LElbowRoll = newValue
        }
    }

    public var RShoulderPitch: Float {
        get {
            return self._raw.RShoulderPitch
        } set {
            self._raw.RShoulderPitch = newValue
        }
    }

    public var RShoulderRoll: Float {
        get {
            return self._raw.RShoulderRoll
        } set {
            self._raw.RShoulderRoll = newValue
        }
    }

    public var RElbowYaw: Float {
        get {
            return self._raw.RElbowYaw
        } set {
            self._raw.RElbowYaw = newValue
        }
    }

    public var RElbowRoll: Float {
        get {
            return self._raw.RElbowRoll
        } set {
            self._raw.RElbowRoll = newValue
        }
    }

    public var LWristYaw: Float {
        get {
            return self._raw.LWristYaw
        } set {
            self._raw.LWristYaw = newValue
        }
    }

    public var RWristYaw: Float {
        get {
            return self._raw.RWristYaw
        } set {
            self._raw.RWristYaw = newValue
        }
    }

    public var computedVars: [String: Any] {
        return [
            "HeadYaw": self._raw.HeadYaw,
            "HeadPitch": self._raw.HeadPitch,
            "LShoulderPitch": self._raw.LShoulderPitch,
            "LShoulderRoll": self._raw.LShoulderRoll,
            "LElbowYaw": self._raw.LElbowYaw,
            "LElbowRoll": self._raw.LElbowRoll,
            "RShoulderPitch": self._raw.RShoulderPitch,
            "RShoulderRoll": self._raw.RShoulderRoll,
            "RElbowYaw": self._raw.RElbowYaw,
            "RElbowRoll": self._raw.RElbowRoll,
            "LWristYaw": self._raw.LWristYaw,
            "RWristYaw": self._raw.RWristYaw
        ]
    }

    public var manipulators: [String: (Any) -> Any] {
        return [:]
    }

    public var validVars: [String: [Any]] {
        return ["_raw": []]
    }

    /**
     * Create a new `wb_sensors_torsojointsensors`.
     */
    public init(HeadYaw: Float = 0.0, HeadPitch: Float = 0.0, LShoulderPitch: Float = 0.0, LShoulderRoll: Float = 0.0, LElbowYaw: Float = 0.0, LElbowRoll: Float = 0.0, RShoulderPitch: Float = 0.0, RShoulderRoll: Float = 0.0, RElbowYaw: Float = 0.0, RElbowRoll: Float = 0.0, LWristYaw: Float = 0.0, RWristYaw: Float = 0.0) {
        self._raw = wb_sensors_torsojointsensors()
        self.HeadYaw = HeadYaw
        self.HeadPitch = HeadPitch
        self.LShoulderPitch = LShoulderPitch
        self.LShoulderRoll = LShoulderRoll
        self.LElbowYaw = LElbowYaw
        self.LElbowRoll = LElbowRoll
        self.RShoulderPitch = RShoulderPitch
        self.RShoulderRoll = RShoulderRoll
        self.RElbowYaw = RElbowYaw
        self.RElbowRoll = RElbowRoll
        self.LWristYaw = LWristYaw
        self.RWristYaw = RWristYaw
    }

    /**
     * Create a new `wb_sensors_torsojointsensors`.
     */
    public init(_ rawValue: wb_sensors_torsojointsensors) {
        self._raw = rawValue
    }

    /**
     * Create a `wb_sensors_torsojointsensors` from a dictionary.
     */
    public init(fromDictionary dictionary: [String: Any?]) {
        self.init()
        guard
            let HeadYaw = dictionary["HeadYaw"] as? Float,
            let HeadPitch = dictionary["HeadPitch"] as? Float,
            let LShoulderPitch = dictionary["LShoulderPitch"] as? Float,
            let LShoulderRoll = dictionary["LShoulderRoll"] as? Float,
            let LElbowYaw = dictionary["LElbowYaw"] as? Float,
            let LElbowRoll = dictionary["LElbowRoll"] as? Float,
            let RShoulderPitch = dictionary["RShoulderPitch"] as? Float,
            let RShoulderRoll = dictionary["RShoulderRoll"] as? Float,
            let RElbowYaw = dictionary["RElbowYaw"] as? Float,
            let RElbowRoll = dictionary["RElbowRoll"] as? Float,
            let LWristYaw = dictionary["LWristYaw"] as? Float,
            let RWristYaw = dictionary["RWristYaw"] as? Float
        else {
            fatalError("Unable to convert \(dictionary) to wb_sensors_torsojointsensors.")
        }
        self.HeadYaw = HeadYaw
        self.HeadPitch = HeadPitch
        self.LShoulderPitch = LShoulderPitch
        self.LShoulderRoll = LShoulderRoll
        self.LElbowYaw = LElbowYaw
        self.LElbowRoll = LElbowRoll
        self.RShoulderPitch = RShoulderPitch
        self.RShoulderRoll = RShoulderRoll
        self.RElbowYaw = RElbowYaw
        self.RElbowRoll = RElbowRoll
        self.LWristYaw = LWristYaw
        self.RWristYaw = RWristYaw
    }

}

extension SENSORSTorsoJointSensors: CustomStringConvertible {

    /**
     * Convert to a description String.
     */
    public var description: String {
        var descString = ""
        descString += "HeadYaw=\(self.HeadYaw)"
        descString += ", "
        descString += "HeadPitch=\(self.HeadPitch)"
        descString += ", "
        descString += "LShoulderPitch=\(self.LShoulderPitch)"
        descString += ", "
        descString += "LShoulderRoll=\(self.LShoulderRoll)"
        descString += ", "
        descString += "LElbowYaw=\(self.LElbowYaw)"
        descString += ", "
        descString += "LElbowRoll=\(self.LElbowRoll)"
        descString += ", "
        descString += "RShoulderPitch=\(self.RShoulderPitch)"
        descString += ", "
        descString += "RShoulderRoll=\(self.RShoulderRoll)"
        descString += ", "
        descString += "RElbowYaw=\(self.RElbowYaw)"
        descString += ", "
        descString += "RElbowRoll=\(self.RElbowRoll)"
        descString += ", "
        descString += "LWristYaw=\(self.LWristYaw)"
        descString += ", "
        descString += "RWristYaw=\(self.RWristYaw)"
        return descString
    }

}

extension SENSORSTorsoJointSensors: Equatable {}

public func == (lhs: SENSORSTorsoJointSensors, rhs: SENSORSTorsoJointSensors) -> Bool {
    return lhs.HeadYaw == rhs.HeadYaw
        && lhs.HeadPitch == rhs.HeadPitch
        && lhs.LShoulderPitch == rhs.LShoulderPitch
        && lhs.LShoulderRoll == rhs.LShoulderRoll
        && lhs.LElbowYaw == rhs.LElbowYaw
        && lhs.LElbowRoll == rhs.LElbowRoll
        && lhs.RShoulderPitch == rhs.RShoulderPitch
        && lhs.RShoulderRoll == rhs.RShoulderRoll
        && lhs.RElbowYaw == rhs.RElbowYaw
        && lhs.RElbowRoll == rhs.RElbowRoll
        && lhs.LWristYaw == rhs.LWristYaw
        && lhs.RWristYaw == rhs.RWristYaw
}

extension wb_sensors_torsojointsensors: Equatable {}

public func == (lhs: wb_sensors_torsojointsensors, rhs: wb_sensors_torsojointsensors) -> Bool {
    return SENSORSTorsoJointSensors(lhs) == SENSORSTorsoJointSensors(rhs)
}
