/*
 * file VisionDetectionGoal.swift
 *
 * This file was generated by classgenerator from vision_detection_goal.gen.
 * DO NOT CHANGE MANUALLY!
 *
 * Copyright © 2020 Carl Lusty. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials
 *    provided with the distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgement:
 *
 *        This product includes software developed by Carl Lusty.
 *
 * 4. Neither the name of the author nor the names of contributors
 *    may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * -----------------------------------------------------------------------
 * This program is free software; you can redistribute it and/or
 * modify it under the above terms or under the terms of the GNU
 * General Public License as published by the Free Software Foundation;
 * either version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see http://www.gnu.org/licenses/
 * or write to the Free Software Foundation, Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

//swiftlint:disable superfluous_disable_command
//swiftlint:disable type_body_length
//swiftlint:disable function_body_length
//swiftlint:disable file_length
//swiftlint:disable line_length
//swiftlint:disable identifier_name

/**
 * Results for the Goal Ray Tracer (guvision). 
 * If two posts are found, then post1 is the left post and post2 is the right.
 */
public struct VisionDetectionGoal {

    public var _raw: wb_vision_detection_goal

    public var sightingType: GoalOptions {
        get {
            return self._raw.sightingType
        } set {
            self._raw.sightingType = newValue
        }
    }

    public var post1: VisionDetectionGoalPost {
        get {
            return VisionDetectionGoalPost(self._raw.post1)
        } set {
            self._raw.post1 = newValue._raw
        }
    }

    public var post2: VisionDetectionGoalPost {
        get {
            return VisionDetectionGoalPost(self._raw.post2)
        } set {
            self._raw.post2 = newValue._raw
        }
    }

    public var computedVars: [String: Any] {
        return [
            "sightingType": self._raw.sightingType,
            "post1": self._raw.post1,
            "post2": self._raw.post2
        ]
    }

    public var manipulators: [String: (Any) -> Any] {
        return [:]
    }

    public var validVars: [String: [Any]] {
        return ["_raw": []]
    }

    /**
     * Create a new `wb_vision_detection_goal`.
     */
    public init(sightingType: GoalOptions = NoGoalDetected, post1: VisionDetectionGoalPost = VisionDetectionGoalPost(wb_vision_detection_goal_post()), post2: VisionDetectionGoalPost = VisionDetectionGoalPost(wb_vision_detection_goal_post())) {
        self._raw = wb_vision_detection_goal()
        self.sightingType = sightingType
        self.post1 = post1
        self.post2 = post2
    }

    /**
     * Create a new `wb_vision_detection_goal`.
     */
    public init(_ rawValue: wb_vision_detection_goal) {
        self._raw = rawValue
    }

    /**
     * Create a `wb_vision_detection_goal` from a dictionary.
     */
    public init(fromDictionary dictionary: [String: Any?]) {
        self.init()
        guard
            let sightingType = dictionary["sightingType"] as? GoalOptions,
            let post1 = (dictionary["post1"] as? [String: Any]).flatMap({ VisionDetectionGoalPost(fromDictionary: $0)  }),
            let post2 = (dictionary["post2"] as? [String: Any]).flatMap({ VisionDetectionGoalPost(fromDictionary: $0)  })
        else {
            fatalError("Unable to convert \(dictionary) to wb_vision_detection_goal.")
        }
        self.sightingType = sightingType
        self.post1 = post1
        self.post2 = post2
    }

}

extension VisionDetectionGoal: CustomStringConvertible {

    /**
     * Convert to a description String.
     */
    public var description: String {
        var descString = ""
        descString += "sightingType=\(self.sightingType.rawValue)"
        descString += ", "
        descString += "post1={" + self.post1.description + "}"
        descString += ", "
        descString += "post2={" + self.post2.description + "}"
        return descString
    }

}

extension VisionDetectionGoal: Equatable {}

public func == (lhs: VisionDetectionGoal, rhs: VisionDetectionGoal) -> Bool {
    return lhs.sightingType == rhs.sightingType
        && lhs.post1 == rhs.post1
        && lhs.post2 == rhs.post2
}

extension wb_vision_detection_goal: Equatable {}

public func == (lhs: wb_vision_detection_goal, rhs: wb_vision_detection_goal) -> Bool {
    return VisionDetectionGoal(lhs) == VisionDetectionGoal(rhs)
}
